/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: ["selector", '[data-theme="dark"] &'],
  theme: {
    extend: {
      fontWeight: {
        black: "800",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        sans: ["var(--font-body)"],
        body: ["var(--font-body)"],
        mono: ["var(--font-mono)"],
      },
      colors: {
        black: "#000000",
        white: "#FFFFFF",
        zap: {
          bg: "var(--color-bg)",
          "bg-alt": "var(--color-bg-alt)",
          "bg-raised": "var(--color-bg-raised)",
          "bg-tile": "var(--color-bg-tile)",
          "bg-overlay": "var(--color-bg-overlay)",
          border: "var(--color-border)",
          "border-bright": "var(--color-border-bright)",
          teal: "var(--color-teal)",
          "teal-dim": "var(--color-teal-dim)",
          live: "var(--color-live)",
          ink: "var(--color-ink)",
          "ink-muted": "var(--color-ink-muted)",
          "ink-faint": "var(--color-ink-faint)",
          brand: "var(--color-brand)",
          "brand-dim": "var(--color-brand-dim)",
          "brand-hover": "var(--color-brand-hover)",
          "brand-light": "var(--color-brand-dim)",
          accent: "var(--color-accent)",
          "accent-dim": "var(--color-accent-dim)",
          "accent-light": "var(--color-accent-dim)",
          success: "var(--color-success)",
          "success-dim": "var(--color-success-dim)",
          warning: "var(--color-warning)",
          "warning-dim": "var(--color-warning-dim)",
          error: "var(--color-error)",
          "error-dim": "var(--color-error-dim)",
          gold: "var(--color-gold)",
          "gold-dim": "var(--color-gold-dim)",
          surface: "var(--color-surface)",
          danger: "var(--color-error)",
        },
      },
      borderRadius: {
        none: "0px",
        sm: "6px",
        DEFAULT: "8px",
        md: "10px",
        lg: "12px",
        xl: "16px",
        "2xl": "22px",
        /** Match global tokens — generous, UI-friendly card corners */
        "3xl": "var(--radius-lg)",
        "4xl": "var(--radius-xl)",
        full: "9999px",
      },
      boxShadow: {
        brutalist: "2px 2px 0px 0px rgba(0,0,0,1)",
        "brutalist-lg": "3px 3px 0px 0px rgba(0,0,0,1)",
        "brutalist-sm": "1.5px 1.5px 0px 0px rgba(0,0,0,1)",
        "brutalist-dark": "2px 2px 0px 0px rgba(161,161,170,0.48)",
        "brutalist-lg-dark": "3px 3px 0px 0px rgba(161,161,170,0.58)",
        "brutalist-sm-dark": "1.5px 1.5px 0px 0px rgba(161,161,170,0.4)",
        "brand-glow": "0 0 20px rgba(0, 212, 255, 0.25)",
        "accent-glow": "0 0 20px rgba(124, 58, 237, 0.25)",
        "gold-glow": "0 0 20px rgba(245, 166, 35, 0.25)",
      },
      borderWidth: {
        3: "3px",
      },
    },
  },
  plugins: [],
};
